version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6-buster
        environment:
          DOCS: True
    steps:
      - checkout
      - run:
          name: Install GPflow
          command: |
            pip install -U pip
            pip install -q git+git://github.com/GPflow/GPflow.git@develop#egg=gpflow
            git clone --branch develop https://github.com/GPflow/GPflow.git
            pip install -q -r GPflow/tests_requirements.txt
      - run:
          name: Make notebooks and move docs
          command: |
            make -C GPflow/doc/source/notebooks -j 4
            rm -r doc
            cp -r GPflow/doc .
            rm -rf GPflow
      - run:
          name: Generate doc rst file
          command: |
            python doc/source/generate_module_rst.py
      - run:
          name: Commit
          command: |
            git config user.email "docs.bot@gpflow.com"
            git config user.name "Docs Bot"
            git add --all
            git commit -m "Update docs [ci skip]"
            git push origin develop

      - run: echo "Docs created successfully"
